modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Leo40Git/CraftableChainmail/issues"
updateJSONURL="https://raw.githubusercontent.com/Leo40Git/CraftableChainmail/meta/update.json"
[[mods]]
    modId="craftablechainmail"
    version="${version}"
    displayName="Leo's Craftable Chainmail"
    logoFile="craftablechainmail.png"
    authors="ADudeCalledLeo (Leo40Git@github)"
    description='''Adds a crafting recipe for chainmail armor.'''
[[dependencies.craftablechainmail]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftablechainmail]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
